### ISSUE TITLE
netLocalGroupList function return very less information

### ISSUE THREAD

**Issue by um3ha4a** [trustedsec/CS-Situational-Awareness-BOF#66] opened 2022-02-14 03:13 UTC
netLocalGroupList function seems have a bug:
beacon> netLocalGroupList
[*] Running netlocalgroup
[+] host called home, sent: 2404 bytes
[+] received output:
Name:      __vmware__
Comment:   VMware User Group
--------------------------------

**Comment by freefirex** [comment] 2022-02-14 14:09
I'm unable to reproduce this.

Please provide the following info:
architecture of your beacon:
full windows version number / build number you executed this on.
How you were connected (external c2, http(s), dns, smb, tcp)

screenshots of both `shell net localgroup` and `netLocalGroupList` being run on the same beacon.

**Comment by freefirex** [comment] 2022-02-21 13:19
I'm closing this after not hearing back for a week.  Please reopen with the requested details if you missed the previous message

**Closed by freefirex** 2022-02-21 13:19 UTC
